# Generated by Django 5.1.7 on 2025-03-17 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VocabularyWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True)),
                ('part_of_speech', models.CharField(max_length=50)),
                ('translation', models.CharField(max_length=255)),
                ('example_sentence', models.TextField()),
                ('example_translation', models.TextField()),
                ('audio_word', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('audio_sentence', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
