# Generated by Django 5.1.7 on 2025-04-14 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_vocabulary', '0002_alter_vocabularyword_example_sentence_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabularyword',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary_words', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vocabularyword',
            name='word',
            field=models.CharField(max_length=100),
        ),
    ]
