# Generated by Django 5.1.7 on 2025-04-14 02:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_vocabulary', '0003_vocabularyword_user_alter_vocabularyword_word'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabularyword',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary_words', to=settings.AUTH_USER_MODEL),
        ),
    ]
