# Generated by Django 5.1.7 on 2025-04-20 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_vocabulary', '0004_alter_vocabularyword_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='vocabularyword',
            name='source_lang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='words_as_source', to='api_vocabulary.language'),
        ),
        migrations.AddField(
            model_name='vocabularyword',
            name='target_lang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='words_as_target', to='api_vocabulary.language'),
        ),
    ]
