# Generated by Django 5.1.7 on 2025-04-20 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_vocabulary', '0005_language_vocabularyword_source_lang_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabularyword',
            name='source_lang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words_as_source', to='api_vocabulary.language'),
        ),
        migrations.AlterField(
            model_name='vocabularyword',
            name='target_lang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words_as_target', to='api_vocabulary.language'),
        ),
    ]
