# Generated by Django 5.1.7 on 2025-05-21 00:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_vocabulary', '0006_alter_vocabularyword_source_lang_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomWordContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('context', models.TextField()),
                ('translation', models.CharField(blank=True, max_length=255, null=True)),
                ('example_sentence', models.TextField(blank=True, null=True)),
                ('example_translation', models.TextField(blank=True, null=True)),
                ('audio_word', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('audio_sentence', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('source_lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_source_words', to='api_vocabulary.language')),
                ('target_lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_target_words', to='api_vocabulary.language')),
            ],
            options={
                'unique_together': {('word', 'source_lang', 'target_lang', 'context')},
            },
        ),
        migrations.CreateModel(
            name='SharedVocabularyWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('translation', models.CharField(max_length=255)),
                ('example_sentence', models.TextField()),
                ('example_translation', models.TextField()),
                ('audio_word', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('audio_sentence', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('source_lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_words_as_source', to='api_vocabulary.language')),
                ('target_lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_words_as_target', to='api_vocabulary.language')),
            ],
            options={
                'unique_together': {('word', 'source_lang', 'target_lang')},
            },
        ),
        migrations.CreateModel(
            name='UserVocabularyWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('custom_content', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_vocabulary.customwordcontent')),
                ('shared_word', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_words', to='api_vocabulary.sharedvocabularyword')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary_words', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'shared_word', 'custom_content')},
            },
        ),
        migrations.DeleteModel(
            name='VocabularyWord',
        ),
    ]
